pages = [{"l":"index.html","n":"Ergo","t":"Ergo","d":"","k":"static"},
{"l":"ergo/security.html","n":"ergo.security","t":"package ergo.security","d":"ergo/security","k":"package"},
{"l":"ergo/security/GroupPermission$.html","n":"GroupPermission","t":"object GroupPermission","d":"ergo/security/GroupPermission$","k":"object"},
{"l":"ergo/security/GroupPermission$.html","n":"apply","t":"def apply(groupId: String): Permission","d":"ergo/security/GroupPermission$","k":"def"},
{"l":"ergo/security/GroupPermission$.html","n":"toSet","t":"def toSet(ids: Iterable[String]): Set[Permission]","d":"ergo/security/GroupPermission$","k":"def"},
{"l":"ergo/security/GroupPermission$.html","n":"toSet","t":"def toSet(one: String, more: String*): Set[Permission]","d":"ergo/security/GroupPermission$","k":"def"},
{"l":"ergo/security/GroupPermission$.html","n":"unapply","t":"def unapply(perm: Permission): Option[String]","d":"ergo/security/GroupPermission$","k":"def"},
{"l":"ergo/security/Permission.html","n":"Permission","t":"trait Permission","d":"ergo/security/Permission","k":"trait"},
{"l":"ergo/security/Permission.html","n":"name","t":"def name: String","d":"ergo/security/Permission","k":"def"},
{"l":"ergo/security/Permission$.html","n":"Permission","t":"object Permission","d":"ergo/security/Permission$","k":"object"},
{"l":"ergo/security/Permission$.html","n":"apply","t":"def apply(name: String): Permission","d":"ergo/security/Permission$","k":"def"},
{"l":"ergo/security/Permission$.html","n":"toSet","t":"def toSet(names: Iterable[String]): Set[Permission]","d":"ergo/security/Permission$","k":"def"},
{"l":"ergo/security/Permission$.html","n":"toSet","t":"def toSet(one: String, more: String*): Set[Permission]","d":"ergo/security/Permission$","k":"def"},
{"l":"ergo/security/Permission$.html","n":"unapply","t":"def unapply(perm: Permission): Option[String]","d":"ergo/security/Permission$","k":"def"},
{"l":"ergo/security/RootContext$.html","n":"RootContext","t":"object RootContext extends SecurityContext","d":"ergo/security/RootContext$","k":"object"},
{"l":"ergo/security/RootContext$.html","n":"test","t":"def test(perm: Permission): Boolean","d":"ergo/security/RootContext$","k":"def"},
{"l":"ergo/security/RootContext$.html","n":"toString","t":"val toString: String","d":"ergo/security/RootContext$","k":"val"},
{"l":"ergo/security/SecurityContext.html","n":"SecurityContext","t":"trait SecurityContext","d":"ergo/security/SecurityContext","k":"trait"},
{"l":"ergo/security/SecurityContext.html","n":"all","t":"def all[T](perms: Set[Permission])(op: => T): T","d":"ergo/security/SecurityContext","k":"def"},
{"l":"ergo/security/SecurityContext.html","n":"all","t":"def all[T](one: Permission, more: Permission*)(op: => T): T","d":"ergo/security/SecurityContext","k":"def"},
{"l":"ergo/security/SecurityContext.html","n":"any","t":"def any[T](perms: Set[Permission])(op: => T): T","d":"ergo/security/SecurityContext","k":"def"},
{"l":"ergo/security/SecurityContext.html","n":"any","t":"def any[T](one: Permission, more: Permission*)(op: => T): T","d":"ergo/security/SecurityContext","k":"def"},
{"l":"ergo/security/SecurityContext.html","n":"apply","t":"def apply[T](perm: Permission)(op: => T): T","d":"ergo/security/SecurityContext","k":"def"},
{"l":"ergo/security/SecurityContext.html","n":"test","t":"def test(perm: Permission): Boolean","d":"ergo/security/SecurityContext","k":"def"},
{"l":"ergo/security/SecurityViolation.html","n":"SecurityViolation","t":"class SecurityViolation(message: String) extends RuntimeException","d":"ergo/security/SecurityViolation","k":"class"},
{"l":"ergo/security/UserContext.html","n":"UserContext","t":"trait UserContext extends SecurityContext","d":"ergo/security/UserContext","k":"trait"},
{"l":"ergo/security/UserContext.html","n":"grant","t":"def grant(perms: Set[Permission]): UserContext","d":"ergo/security/UserContext","k":"def"},
{"l":"ergo/security/UserContext.html","n":"grant","t":"def grant(one: Permission, more: Permission*): UserContext","d":"ergo/security/UserContext","k":"def"},
{"l":"ergo/security/UserContext.html","n":"groupId","t":"def groupId: String","d":"ergo/security/UserContext","k":"def"},
{"l":"ergo/security/UserContext.html","n":"permissions","t":"def permissions: Set[Permission]","d":"ergo/security/UserContext","k":"def"},
{"l":"ergo/security/UserContext.html","n":"revoke","t":"def revoke(perms: Set[Permission]): UserContext","d":"ergo/security/UserContext","k":"def"},
{"l":"ergo/security/UserContext.html","n":"revoke","t":"def revoke(one: Permission, more: Permission*): UserContext","d":"ergo/security/UserContext","k":"def"},
{"l":"ergo/security/UserContext.html","n":"userId","t":"def userId: String","d":"ergo/security/UserContext","k":"def"},
{"l":"ergo/security/UserContext$.html","n":"UserContext","t":"object UserContext","d":"ergo/security/UserContext$","k":"object"},
{"l":"ergo/security/UserContext$.html","n":"apply","t":"def apply(userId: String, groupId: String): UserContext","d":"ergo/security/UserContext$","k":"def"},
{"l":"ergo/security/UserContext$.html","n":"apply","t":"def apply(userId: String, groupId: String, permissions: Set[Permission]): UserContext","d":"ergo/security/UserContext$","k":"def"},
{"l":"ergo/security/UserContext$.html","n":"apply","t":"def apply(userId: String, groupId: String, one: Permission, more: Permission*): UserContext","d":"ergo/security/UserContext$","k":"def"},
{"l":"ergo/security/UserContext$.html","n":"unapply","t":"def unapply(security: UserContext): Option[(String, String, Set[Permission])]","d":"ergo/security/UserContext$","k":"def"},
{"l":"ergo/security/UserPermission$.html","n":"UserPermission","t":"object UserPermission","d":"ergo/security/UserPermission$","k":"object"},
{"l":"ergo/security/UserPermission$.html","n":"apply","t":"def apply(userId: String): Permission","d":"ergo/security/UserPermission$","k":"def"},
{"l":"ergo/security/UserPermission$.html","n":"toSet","t":"def toSet(ids: Iterable[String]): Set[Permission]","d":"ergo/security/UserPermission$","k":"def"},
{"l":"ergo/security/UserPermission$.html","n":"toSet","t":"def toSet(one: String, more: String*): Set[Permission]","d":"ergo/security/UserPermission$","k":"def"},
{"l":"ergo/security/UserPermission$.html","n":"unapply","t":"def unapply(perm: Permission): Option[String]","d":"ergo/security/UserPermission$","k":"def"},
{"l":"docs/index.html","n":"Ergo","t":"Ergo","d":"","k":"static"}];